auth-integration files
prajj07/user-auth pull request #9
Opened 2024-06-19 07:15 UTC by prajj07

2024-06-24 07:14 UTC, hari-dataequinox requested changes

2024-06-24 07:14 UTC, hari-dataequinox commented on app/layout.tsx
> +      <nav className="flex justify-center gap-4 p-4 bg-gray-100">
Can you take a look at Shadcn [Menubar](https://ui.shadcn.com/docs/components/menubar) component and see if we can integrate them?

2024-06-24 07:14 UTC, hari-dataequinox commented on app/page.tsx
> +import { Poppins } from "next/font/google";
Can we configure fonts on a global level , like in a generic stylesheet ? Or in the tailwind configuration ?

2024-06-24 11:46 UTC, hari-dataequinox approved these changes

2024-06-26 07:06 UTC, prajj07 commented
![Screenshot from 2024-06-26 12-35-37](https://github.com/prajj07/user-auth/assets/83826853/d4c85530-d03e-4a4d-95b1-532a59304ef4)

2024-06-26 12:13 UTC, merged